LEGACY_COURSES = [
    {
      "id": "sample-course",
      "title": "SAMPLE COURSE",
      "description": "A 30-second demo lesson to experience the AI-monitored learning environment.",
      "image": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=250&fit=crop",
      "isDemo": True,
      "modules": [
        {
          "id": "demo-lesson",
          "title": "Demo Lesson",
          "description": "A 30-second sample video to test the system.",
          "videoId": "tWoo8i_VkvI",
        }
      ]
    },
    {
      "id": "data-analyst",
      "title": "Data Analyst Bootcamp",
      "description": "Master data visualization, SQL, and Excel for analytics.",
      "image": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",
      "modules": [
        { "id": "da-1", "title": "FREE Data Analyst Bootcamp!!", "description": "Kickstart your journey as a data analyst with this comprehensive bootcamp intro.", "videoId": "rGx1QNdYzvs" },
        { "id": "da-2", "title": "How to Become a Data Analyst in 2023", "description": "A complete guide to becoming a data analyst for free.", "videoId": "CUBfrdDwznQ" },
        { "id": "da-3", "title": "Installing MySQL and Creating Databases", "description": "Setup your environment for SQL learning.", "videoId": "wgRwITQHszU" },
        { "id": "da-4", "title": "Select Statement in MySQL", "description": "Learn the most fundamental SQL command.", "videoId": "HYD8KjPB9F8" },
        { "id": "da-5", "title": "Where Clause in MySQL", "description": "Filter your data with precision.", "videoId": "MARn_mssG4A" },
        { "id": "da-6", "title": "Group By + Order By in MySQL", "description": "Organize and sort your database results.", "videoId": "zgYqUP_PhQo" },
        { "id": "da-7", "title": "Having vs Where in MySQL", "description": "Understand the difference between filtering before and after aggregation.", "videoId": "dCNjUOc1cBY" },
        { "id": "da-8", "title": "Limit + Aliasing in MySQL", "description": "Formatting and restricting your data output.", "videoId": "ZnAydTqCtFU" },
        { "id": "da-9", "title": "Joins in MySQL", "description": "Connecting multiple tables together.", "videoId": "lXQzD09BOH0" },
        { "id": "da-10", "title": "Unions in MySQL", "description": "Combining results from multiple queries.", "videoId": "iTQW_nDp938" },
        { "id": "da-11", "title": "String Functions in MySQL", "description": "Manipulating text data in SQL.", "videoId": "KRXSJb9ql1Y" },
        { "id": "da-12", "title": "Case Statements in MySQL", "description": "Adding logic to your SQL queries.", "videoId": "RYIiOG4LsvQ" },
        { "id": "da-13", "title": "Subqueries in MySQL", "description": "Queries inside queries for complex data retrieval.", "videoId": "Vj6RqA_X-IE" },
        { "id": "da-14", "title": "Window Functions in MySQL", "description": "Advanced analytical functions for data rows.", "videoId": "7NBt0V8ebGk" },
        { "id": "da-15", "title": "CTEs in MySQL", "description": "Common Table Expressions for cleaner SQL code.", "videoId": "UC7uvOqcUTs" },
        { "id": "da-16", "title": "Temp Tables in MySQL", "description": "Working with temporary data storage.", "videoId": "uEk07jXdKOo" },
        { "id": "da-17", "title": "Stored Procedures in MySQL", "description": "Automating reusable SQL scripts.", "videoId": "7vnxpcqmqNQ" },
        { "id": "da-18", "title": "Triggers and Events in MySQL", "description": "Executing code automatically based on database actions.", "videoId": "QMUZ5HfWMRc" },
        { "id": "da-19", "title": "Data Cleaning in MySQL", "description": "Full project focusing on cleaning real-world data.", "videoId": "4UltKCnnnTA" },
        { "id": "da-20", "title": "MySQL Exploratory Data Analysis", "description": "Full project for analyzing and discovering patterns in data.", "videoId": "QYd-RtK58VQ" },
        { "id": "da-21", "title": "Pivot Tables in Excel", "description": "The most powerful tool for Excel data analysis.", "videoId": "lH7HfwUFnYA" },
        { "id": "da-22", "title": "Formulas in Excel", "description": "Mastering calculations in spreadsheets.", "videoId": "XRPyj7cKVsQ" },
        { "id": "da-23", "title": "XLOOKUP in Excel", "description": "The modern way to find data in Excel.", "videoId": "Z7hPEwCzk2s" },
        { "id": "da-24", "title": "Conditional Formatting in Excel", "description": "Visualize data patterns with colors.", "videoId": "_eZRkmRfVTM" },
        { "id": "da-25", "title": "Charts in Excel", "description": "Creating professional data visualizations.", "videoId": "gMAHXrty6wI" },
        { "id": "da-26", "title": "Cleaning Data in Excel", "description": "Prepare messy Excel data for analysis.", "videoId": "_jmiEGZ6PIY" },
        { "id": "da-27", "title": "Full Project in Excel", "description": "A complete start-to-finish data analysis project in Excel.", "videoId": "opJgMj1IUrc" },
        { "id": "da-28", "title": "Install Tableau & First Visualization", "description": "Get started with the leading BI tool.", "videoId": "6xv1KvCMF1Q" },
        { "id": "da-29", "title": "Calculated Fields & Bins in Tableau", "description": "Adding custom logic to your Tableau viz.", "videoId": "f6qxxtWkaUg" },
        { "id": "da-30", "title": "Create Visualizations in Tableau", "description": "Building various types of Tableau charts.", "videoId": "ebjDwX8sUMk" },
        { "id": "da-31", "title": "Joins in Tableau", "description": "Combining data sources within Tableau.", "videoId": "A4SVUF-fTwc" },
        { "id": "da-32", "title": "Full Beginner Project in Tableau", "description": "Build your first Tableau dashboard from scratch.", "videoId": "zOR0-nygfDE" },
        { "id": "da-33", "title": "Install Power BI & First Viz", "description": "Getting started with Microsoft Power BI.", "videoId": "g0m5sEHPU-s" },
        { "id": "da-34", "title": "Power Query in Power BI", "description": "ETL and data transformation in Power BI.", "videoId": "gP-AxNi6uxo" },
        { "id": "da-35", "title": "Relationships in Power BI", "description": "Creating data models for business intelligence.", "videoId": "sW5LoDA1ssM" },
        { "id": "da-36", "title": "DAX in Power BI", "description": "Data Analysis Expressions for advanced metrics.", "videoId": "vcijg0gUXSg" },
        { "id": "da-37", "title": "Drill Down in Power BI", "description": "Interactive data exploration techniques.", "videoId": "ulFY20KTzFQ" },
        { "id": "da-38", "title": "Conditional Formatting in Power BI", "description": "Highlighting key metrics automatically.", "videoId": "m0h3Ghl6mgY" },
        { "id": "da-39", "title": "Bins and Lists in Power BI", "description": "Categorizing data for better insights.", "videoId": "9j_EBt3RNrs" },
        { "id": "da-40", "title": "Popular Visualizations in Power BI", "description": "Mastering standard Power BI charts.", "videoId": "3NV5Jtbhfcw" },
        { "id": "da-41", "title": "Full Power BI Guided Project", "description": "Complete business intelligence project walkthrough.", "videoId": "pixlHHe_lNQ" },
        { "id": "da-42", "title": "Installing Jupyter/Anaconda", "description": "Setting up your Python environment.", "videoId": "WUeBzT43JyY" },
        { "id": "da-43", "title": "Variables in Python", "description": "The building blocks of Python programming.", "videoId": "pHOH7UfOhbE" },
        { "id": "da-44", "title": "Data Types in Python", "description": "Understanding strings, integers, and floats.", "videoId": "ppsCxnNm-JI" },
        { "id": "da-45", "title": "Operators in Python", "description": "Comparison, logical, and membership operators.", "videoId": "lPVke-p4S7s" },
        { "id": "da-46", "title": "If Else Statements in Python", "description": "Control flow and decision making.", "videoId": "-BOBedcjySI" },
        { "id": "da-47", "title": "For Loops in Python", "description": "Iterating through sequences of data.", "videoId": "zmIdC0_0BgY" },
        { "id": "da-48", "title": "While Loops in Python", "description": "Repeating code based on conditions.", "videoId": "ECduJk00mUU" },
        { "id": "da-49", "title": "Functions in Python", "description": "Writing modular and reusable code.", "videoId": "zvzjaqMBEso" },
        { "id": "da-50", "title": "Converting Data Types", "description": "Type casting in Python.", "videoId": "B63bN2cLVLM" },
        { "id": "da-51", "title": "BMI Calculator Project", "description": "Simple Python project for beginners.", "videoId": "ey1VNjU0YbM" },
        { "id": "da-52", "title": "Automated File Sorter project", "description": "Automate your OS tasks with Python.", "videoId": "gs0FNQR0njI" },
        { "id": "da-53", "title": "Inspecting Web Pages (HTML)", "description": "Understand website structure for scraping.", "videoId": "q-kbzWjyPak" },
        { "id": "da-54", "title": "BeautifulSoup + Requests", "description": "The fundamentals of web scraping.", "videoId": "bargNl2WeN4" },
        { "id": "da-55", "title": "Find and Find_All", "description": "Extracting specific elements from web pages.", "videoId": "xjA1HjvmoMY" },
        { "id": "da-56", "title": "Scraping Data from Real Website", "description": "End-to-end web scraping project.", "videoId": "8dTpNajxaH0" },
        { "id": "da-57", "title": "Reading Files in Pandas", "description": "Importing CSV, Excel, and JSON into Python.", "videoId": "dUpyC40cF6Q" },
        { "id": "da-58", "title": "Filtering Columns and Rows", "description": "Selecting specific data in Pandas DataFrames.", "videoId": "kB7FV-ijdqE" },
        { "id": "da-59", "title": "Indexes in Pandas", "description": "Efficiently navigating your data.", "videoId": "mBCG9J1TVTc" },
        { "id": "da-60", "title": "Group By & Aggregates", "description": "Summarizing data with Python.", "videoId": "VRmXto2YA2I" },
        { "id": "da-61", "title": "Merging DataFrames", "description": "Python equivalent of SQL Joins.", "videoId": "TPivN7tpdwc" },
        { "id": "da-62", "title": "Visualizations in Pandas", "description": "Plotting directly from your DataFrame.", "videoId": "JpSMse3eVVg" },
        { "id": "da-63", "title": "Data Cleaning in Pandas", "description": "The most important step in data analysis.", "videoId": "bDhvCp3_lYw" },
        { "id": "da-64", "title": "Exploratory Data Analysis", "description": "Uncovering trends and patterns with Pandas.", "videoId": "Liv6eeb1VfE" },
        { "id": "da-65", "title": "Amazon Web Scraping Project", "description": "Build a portfolio project with real data.", "videoId": "HiOtQMcI5wg" },
        { "id": "da-66", "title": "Crypto API Pull Project", "description": "Connecting to live APIs for data analysis.", "videoId": "KB2CtEDrglY" },
        { "id": "da-67", "title": "Create Portfolio Website", "description": "Showcase your work to employers.", "videoId": "ocdwh0KYeUs" },
        { "id": "da-68", "title": "Perfect Data Analyst Resume", "description": "Job hunting tips and templates.", "videoId": "WizLaDdsHUs" },
        { "id": "da-69", "title": "Easy SQL Interview Questions", "description": "Practice for entry-level roles.", "videoId": "ZHaYOC0H5KE" },
        { "id": "da-70", "title": "Medium SQL Interview Questions", "description": "Level up your SQL skills.", "videoId": "fT-8mRf_-Hk" },
        { "id": "da-71", "title": "Hard SQL Interview Questions", "description": "Prepare for senior-level interviews.", "videoId": "I0_ca6iyo6w" },
        { "id": "da-72", "title": "Very Hard SQL Questions", "description": "Expert-level SQL challenges.", "videoId": "KZKizyBS9YM" },
        { "id": "da-73", "title": "Azure Account Setup", "description": "Cloud computing for data analysts.", "videoId": "ZYps6TmBkWk" },
        { "id": "da-74", "title": "Blob Storage in Azure", "description": "Storing unstructured data in the cloud.", "videoId": "sEImMaovc1Q" },
        { "id": "da-75", "title": "Azure SQL Databases", "description": "Relational databases in the cloud.", "videoId": "9ur0OpMADuM" },
        { "id": "da-76", "title": "Azure Data Factory", "description": "Orchestrating data workflows.", "videoId": "sge9qTf8GdY" },
        { "id": "da-77", "title": "Azure Synapse Analytics", "description": "Enterprise data warehousing.", "videoId": "vDVcXXfc9e8" },
        { "id": "da-78", "title": "AWS Setup & UI Walkthrough", "description": "Introduction to Amazon Web Services.", "videoId": "YSjbGET6R1A" },
        { "id": "da-79", "title": "S3 Storage in AWS", "description": "Working with AWS cloud storage.", "videoId": "hgaVi4sOHkM" },
        { "id": "da-80", "title": "Amazon Athena", "description": "Serverless SQL on S3 data.", "videoId": "K2GfrERtliU" },
        { "id": "da-81", "title": "AWS Glue", "description": "Serverless data integration.", "videoId": "AycpRKyRagE" },
        { "id": "da-82", "title": "AWS Quicksight", "description": "Business intelligence in AWS.", "videoId": "rxyLC247h6E" },
        { "id": "da-83", "title": "LinkedIn Job Hunting Tips", "description": "Networking strategies for data analysts.", "videoId": "7uH7_DThtX0" },
        { "id": "da-84", "title": "Bootcamp Certification!", "description": "Final steps and graduation.", "videoId": "28r412KFhG4" }
      ]
    },
    {
      "id": "data-scientist",
      "title": "Data Science Specialization",
      "description": "Learn Python, Machine Learning, and Statistical modeling.",
      "image": "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=400&h=250&fit=crop",
      "modules": [
        { "id": "ds-1", "title": "Introduction to Data Science", "description": "Overview of the field.", "videoId": "QISvmiwOIYI", "startTime": 0 },
        { "id": "ds-2", "title": "Data science pipeline demo", "description": "Real-world deployment.", "videoId": "QISvmiwOIYI", "startTime": 171 },
        { "id": "ds-3", "title": "What Is Data Science?", "description": "Definitions and concepts.", "videoId": "QISvmiwOIYI", "startTime": 358 },
        { "id": "ds-4", "title": "Scientist Vs Analyst", "description": "Career path comparison.", "videoId": "QISvmiwOIYI", "startTime": 487 },
        { "id": "ds-5", "title": "NumPy Fundamentals", "description": "Array basics.", "videoId": "QISvmiwOIYI", "startTime": 832 },
        { "id": "ds-6", "title": "Data Science Life Cycle", "description": "Phase-by-phase breakdown.", "videoId": "QISvmiwOIYI", "startTime": 1162 },
        { "id": "ds-7", "title": "Prerequisites", "description": "What you need to know.", "videoId": "QISvmiwOIYI", "startTime": 1429 },
        { "id": "ds-8", "title": "Data Science Tools", "description": "Tech stack overview.", "videoId": "QISvmiwOIYI", "startTime": 1621 },
        { "id": "ds-9", "title": "Python For Data Science", "description": "Language basics.", "videoId": "QISvmiwOIYI", "startTime": 1781 },
        { "id": "ds-10", "title": "Mathematics In Data Science", "description": "Core math concepts.", "videoId": "QISvmiwOIYI", "startTime": 2187 },
        { "id": "ds-11", "title": "NumPy Operations", "description": "Special arrays.", "videoId": "QISvmiwOIYI", "startTime": 2767 },
        { "id": "ds-12", "title": "Statistical Analysis", "description": "Business applications.", "videoId": "QISvmiwOIYI", "startTime": 2997 },
        { "id": "ds-13", "title": "Roadmap For 2026", "description": "Future-proofing your career.", "videoId": "QISvmiwOIYI", "startTime": 4407 },
        { "id": "ds-14", "title": "Reshaping & Broadcasting", "description": "Advanced NumPy.", "videoId": "QISvmiwOIYI", "startTime": 4576 },
        { "id": "ds-15", "title": "Linear Algebra", "description": "NumPy utilities.", "videoId": "QISvmiwOIYI", "startTime": 6110 },
        { "id": "ds-16", "title": "Excel for Data Analytics", "description": "Using Excel for DS.", "videoId": "QISvmiwOIYI", "startTime": 6118 },
        { "id": "ds-17", "title": "Pandas Series & DataFrames", "description": "Handling tabular data.", "videoId": "QISvmiwOIYI", "startTime": 7539 },
        { "id": "ds-18", "title": "Data I/O in Pandas", "description": "Practical reading/writing.", "videoId": "QISvmiwOIYI", "startTime": 9250 },
        { "id": "ds-19", "title": "DataFrame EDA", "description": "Exploration techniques.", "videoId": "QISvmiwOIYI", "startTime": 10872 },
        { "id": "ds-20", "title": "Feature Engineering", "description": "Cleaning and indexing.", "videoId": "QISvmiwOIYI", "startTime": 12326 },
        { "id": "ds-21", "title": "GroupBy & Pivot Tables", "description": "Advanced Pandas manipulation.", "videoId": "QISvmiwOIYI", "startTime": 15975 },
        { "id": "ds-22", "title": "Concatenation & Merges", "description": "Combining datasets.", "videoId": "QISvmiwOIYI", "startTime": 18073 },
        { "id": "ds-23", "title": "Matplotlib Fundamentals", "description": "Creating basic charts.", "videoId": "QISvmiwOIYI", "startTime": 19768 },
        { "id": "ds-24", "title": "Seaborn & Plotly", "description": "Advanced visualizations.", "videoId": "QISvmiwOIYI", "startTime": 22787 },
        { "id": "ds-25", "title": "Statistics Foundations", "description": "Variables and tendency.", "videoId": "QISvmiwOIYI", "startTime": 30100 },
        { "id": "ds-26", "title": "Distributions & Correlation", "description": "Probability basics.", "videoId": "QISvmiwOIYI", "startTime": 33306 },
        { "id": "ds-27", "title": "Numpy Mastery", "description": "Deep dive into NumPy.", "videoId": "QISvmiwOIYI", "startTime": 53269 },
        { "id": "ds-28", "title": "Pandas Deep Dive", "description": "Advanced operations.", "videoId": "QISvmiwOIYI", "startTime": 64404 },
        { "id": "ds-29", "title": "Statistics for DS", "description": "Comprehensive stats module.", "videoId": "QISvmiwOIYI", "startTime": 66743 },
        { "id": "ds-30", "title": "Types Of Distribution", "description": "In-depth statistics.", "videoId": "QISvmiwOIYI", "startTime": 68110 },
        { "id": "ds-31", "title": "Chi-Square Distribution", "description": "Specific statistical tests.", "videoId": "QISvmiwOIYI", "startTime": 69545 },
        { "id": "ds-32", "title": "Binomial Distribution", "description": "Probability in depth.", "videoId": "QISvmiwOIYI", "startTime": 69848 },
        { "id": "ds-33", "title": "Poisson Distribution", "description": "Modeling events.", "videoId": "QISvmiwOIYI", "startTime": 70148 },
        { "id": "ds-34", "title": "Inferential Statistics", "description": "Drawing conclusions.", "videoId": "QISvmiwOIYI", "startTime": 70322 },
        { "id": "ds-35", "title": "R Squared Error", "description": "Model evaluation.", "videoId": "QISvmiwOIYI", "startTime": 70654 },
        { "id": "ds-36", "title": "Mean Squared Error", "description": "Cost functions.", "videoId": "QISvmiwOIYI", "startTime": 71691 },
        { "id": "ds-37", "title": "Probability Density", "description": "PDF with examples.", "videoId": "QISvmiwOIYI", "startTime": 73586 },
        { "id": "ds-38", "title": "Cumulative Distribution", "description": "CDF tutorial.", "videoId": "QISvmiwOIYI", "startTime": 75017 },
        { "id": "ds-39", "title": "Conditional Probability", "description": "Dependencies in data.", "videoId": "QISvmiwOIYI", "startTime": 76862 },
        { "id": "ds-40", "title": "Bayes Theorem", "description": "Foundational probability law.", "videoId": "QISvmiwOIYI", "startTime": 77245 },
        { "id": "ds-41", "title": "Learning Paradigms", "description": "Supervised vs Unsupervised.", "videoId": "QISvmiwOIYI", "startTime": 77529 },
        { "id": "ds-42", "title": "Intro to NLP", "description": "Natural Language Processing.", "videoId": "QISvmiwOIYI", "startTime": 79706 },
        { "id": "ds-43", "title": "Deep Learning", "description": "Intro to Neural Networks.", "videoId": "QISvmiwOIYI", "startTime": 80181 },
        { "id": "ds-44", "title": "Top 10 DS Projects", "description": "Portfolio inspiration.", "videoId": "QISvmiwOIYI", "startTime": 80983 },
        { "id": "ds-45", "title": "Interview Questions", "description": "Career preparation.", "videoId": "QISvmiwOIYI", "startTime": 83969 }
      ]
    }
]
