import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

BASE = os.path.dirname(__file__)
DIAG = os.path.join(BASE, "diagrams")
OUT  = os.path.join(BASE, "INTERNIXA_FINAL_REPORT.docx")
doc  = Document(OUT)

def para(text="", bold=False, italic=False, size=12, align="left", color=None, space_before=0, space_after=6):
    p = doc.add_paragraph()
    p.alignment = {"left":WD_ALIGN_PARAGRAPH.LEFT,"center":WD_ALIGN_PARAGRAPH.CENTER,
                   "justify":WD_ALIGN_PARAGRAPH.JUSTIFY}[align]
    p.paragraph_format.space_before = Pt(space_before)
    p.paragraph_format.space_after  = Pt(space_after)
    p.paragraph_format.line_spacing = Pt(18)
    if text:
        run = p.add_run(text)
        run.bold=bold; run.italic=italic
        run.font.name="Times New Roman"; run.font.size=Pt(size)
        if color: run.font.color.rgb=RGBColor(*color)
    return p

def ch(num,title):
    doc.add_page_break()
    para(f"CHAPTER {num}",bold=True,size=14,align="center",space_before=24,space_after=4)
    para(title.upper(),bold=True,size=14,align="center",space_before=0,space_after=18)

def sec(num,title): para(f"{num}  {title}",bold=True,size=12,space_before=12,space_after=6)
def sub(num,title): para(f"{num}  {title}",bold=True,italic=True,size=12,space_before=8,space_after=4)
def body(t):        para(t,size=12,align="justify",space_after=6)
def bullet(t):      para(f"  •  {t}",size=11,align="left",space_after=3)

def fig(fname,caption):
    p=doc.add_paragraph(); p.alignment=WD_ALIGN_PARAGRAPH.CENTER
    path=os.path.join(DIAG,fname)
    if os.path.exists(path): p.add_run().add_picture(path,width=Inches(5.5))
    para(caption,italic=True,size=11,align="center",space_before=2,space_after=12)

def tbl(headers,rows,caption):
    if caption: para(caption,bold=True,italic=True,size=11,align="center",space_before=8,space_after=4)
    t=doc.add_table(rows=1+len(rows),cols=len(headers)); t.style="Table Grid"
    t.alignment=WD_TABLE_ALIGNMENT.CENTER
    for i,h in enumerate(t.rows[0].cells):
        h.text=headers[i]
        for r in h.paragraphs[0].runs: r.bold=True; r.font.size=Pt(9)
        shd=OxmlElement('w:shd'); shd.set(qn('w:fill'),'BFD7FF'); shd.set(qn('w:val'),'clear')
        h._tc.get_or_add_tcPr().append(shd)
    for ri,row in enumerate(rows):
        for ci,cell in enumerate(row):
            c=t.rows[ri+1].cells[ci]; c.text=str(cell)
            for r in c.paragraphs[0].runs: r.font.size=Pt(9)
    doc.add_paragraph()

# ═══ CHAPTER 3 ═══════════════════════════════════════════════════════════════
ch(3,"Proposed System")

sec("3.1","Existing System")
sub("3.1.1","Working")
body("Contemporary Learning Management Systems (LMS) such as Moodle, Canvas, and Blackboard — and commercial MOOC platforms such as Coursera and Udemy — operate on a fundamentally passive content delivery model. A typical user journey on these platforms proceeds as follows: the student authenticates, navigates to a course, and initiates video playback through an HTML5 video element hosted on a Content Delivery Network (CDN). The platform logs a video view event upon play initiation and records playback progress at fixed intervals via JavaScript event listeners. Quiz modules, if present, are delivered separately and do not require demonstrable engagement with the video content to unlock.")
body("Content recommendations are generated by collaborative filtering algorithms based on historical consumption patterns, and any AI chatbot assistance is powered by general-purpose language models with no contextual grounding in the specific course material. Certificates are issued automatically once a student completes all modules in the defined course sequence, with completion defined strictly by playback progress rather than any measure of cognitive engagement. The entire system is designed for content delivery efficiency, not learning verification.")
fig("fig3_1_traditional.png","Fig 3.1 – Traditional LMS Architecture")

sub("3.1.2","Drawbacks")
body("The passive architecture of existing LMS platforms produces several critical and well-documented drawbacks:")
for d in [
    "No Engagement Enforcement: The platform has no technical mechanism to verify that a student is present and attentive during video playback. A video can be played to completion by an unattended device, earning the student full credit.",
    "Generic AI Assistance: AI chatbots on existing platforms (e.g., Coursera's AI Coach) are powered by general-purpose language models that frequently provide answers inconsistent with or contradictory to the specific pedagogical framing of the course material.",
    "Unverified Certifications: Certificates issued by major platforms certify only that a student completed a sequence of modules within a defined time window, not that they acquired the corresponding knowledge or demonstrated active engagement.",
    "No Collaborative Intelligence: Existing platforms provide no mechanism for instructors to monitor the real-time engagement of participants during live or synchronous sessions, making it impossible to identify disengaged students and intervene proactively.",
    "Motivational Architecture Deficiency: Linear content delivery without gamification, competitive elements, or dynamic rewards produces low retention. The absence of social comparison mechanisms removes a powerful intrinsic motivator from the learning experience.",
]:
    bullet(d)

sec("3.2","Proposed System")
sub("3.2.1","Overview")
body("Internixa represents a fundamental reimagining of the e-learning platform architecture, replacing the passive content delivery model with a closed-loop AI learning ecosystem in which every component of the platform actively contributes to the verification and reinforcement of genuine student engagement. The system is built around three core pillars: edge-deployed computer vision for real-time attention monitoring, Retrieval-Augmented Generation for context-locked AI assistance, and a gamified reward architecture grounded in verified engagement metrics.")
body("At the architectural level, Internixa is structured as a decoupled, cloud-native application. The React 19 frontend, deployed on Vercel's global edge network, handles all user interaction and all client-side AI processing. The Python FastAPI backend, deployed on Railway's containerised infrastructure, manages authentication, data persistence, certificate generation, and AI orchestration. A Pinecone serverless vector index stores course transcript embeddings, and a MongoDB Atlas cluster provides the primary operational data store. This separation of concerns ensures horizontal scalability, independent deployability, and clear security boundaries.")
fig("fig3_2_arch.png","Fig 3.2 – Internixa 5-Layer Architecture")

sub("3.2.2","Advantages")
for a in [
    "Active Engagement Enforcement: The MediaPipe monitoring layer creates genuine academic friction — students cannot passively consume content. Every second of playback corresponds to a verified second of student attention.",
    "Context-Locked AI Integrity: The RAG pipeline ensures that AI assistance is always grounded in course content, preventing academic dishonesty and improving the pedagogical relevance of AI responses.",
    "Verified, Tamper-Proof Certification: Certificates are issued exclusively upon achieving a minimum verified engagement threshold, making them a reliable signal of genuine course completion.",
    "Privacy-Preserving Architecture: All video processing occurs on the student's device; only derived metadata is transmitted to the backend, ensuring GDPR-compliant data minimisation.",
    "Gamified Motivation: The Focus Points system and leaderboard leverage established principles of self-determination theory to create intrinsic motivation aligned with genuine learning behaviours.",
    "Live Collaborative Intelligence: WebRTC meetings with real-time host HUD analytics enable instructors to monitor and respond to engagement patterns during synchronous sessions.",
]:
    bullet(a)

sec("3.3","System Architecture")
sub("3.3.1","Block Diagram")
body("The Internixa architecture is organised into five distinct functional layers, each responsible for a specific domain of system functionality. The layers are ordered from the user-facing presentation layer to the persistent data layer, with well-defined interfaces between each adjacent pair.")
fig("fig3_2_arch.png","Fig 3.2 – Internixa 5-Layer Architecture Block Diagram")

sub("3.3.2","DFD Level 0 – Context Diagram")
body("The Level 0 Data Flow Diagram presents the highest-level view of the Internixa system, showing the external entities that interact with it and the primary data flows between those entities and the system boundary. External entities include the Student (the primary user), the Recruiter (posting internship opportunities), the Gemini AI Service (providing LLM inference), and the Camera (providing the live video feed for AI monitoring).")
fig("fig3_3_dfd0.png","Fig 3.3 – DFD Level 0 (Context Diagram)")

sub("3.3.3","DFD Level 1 – Detailed Flow")
body("The Level 1 DFD decomposes the INTERNIXA system into its eight primary processing modules, showing the data flows between modules and the external data stores that support them. Each process represents a distinct functional subsystem of the platform.")
fig("fig3_4_dfd1.png","Fig 3.4 – DFD Level 1 (Detailed Data Flow Diagram)")

sec("3.4","Methodology / Algorithm")
sub("3.4.1","MediaPipe Face Mesh Pipeline")
body("The attention monitoring pipeline begins with the acquisition of a live video frame from the student's webcam via the browser's MediaDevices.getUserMedia() API. Each frame is passed to the MediaPipe Face Mesh model, which executes inference within a WebAssembly (WASM) module accelerated by WebGL. The model returns a set of 468 three-dimensional landmark coordinates, each normalised to the range [0,1] relative to the detected face bounding box. This normalisation ensures robustness against variation in the student's distance from the camera and the camera's field of view.")
body("The 468 landmarks are indexed according to MediaPipe's published canonical face topology. Specific landmark indices are selected for the EAR and gaze calculations: the left eye uses indices 33, 133, 145, 158, 159, and 144; the right eye uses indices 263, 362, 374, 380, 385, and 386; the nose tip uses index 4. The entire pipeline — from frame capture to attention state output — completes within approximately 28 milliseconds on a standard consumer CPU, achieving approximately 35 FPS effective throughput.")
fig("fig3_5_facemesh.png","Fig 3.5 – MediaPipe Face Mesh (468 Landmarks)")

sub("3.4.2","Eye Aspect Ratio (EAR) Formula")
body("The Eye Aspect Ratio (EAR) provides a scalar measure of eye openness computed from six facial landmark coordinates. For each eye, the formula calculates the ratio of the sum of two vertical eyelid distances to twice the horizontal eye width:")
para("EAR  =  ( ||p₁₅₉ − p₁₄₅||  +  ||p₁₅₈ − p₁₄₄|| )  /  ( 2  ×  ||p₃₃ − p₁₃₃|| )",
     bold=True, size=12, align="center", space_before=8, space_after=8, color=(79,70,229))
body("Where p₃₃ denotes the left eye inner corner landmark, p₁₃₃ the left eye outer corner, p₁₅₉ and p₁₄₅ are the upper and lower eyelid landmarks at the medial position, and p₁₅₈ and p₁₄₄ are the upper and lower eyelid landmarks at the lateral position. The denominator normalises the ratio against the horizontal eye width, providing invariance to head scale. For a fully open eye, EAR typically ranges between 0.25 and 0.35. A blink event causes EAR to drop sharply toward zero. Internixa applies the threshold EAR < 0.20 for three or more consecutive frames to classify the eye state as closed, triggering the distraction state machine and pausing video playback.")
fig("fig3_6_ear.png","Fig 3.6 – Eye Aspect Ratio (EAR) Landmark Diagram")

sub("3.4.3","Gaze Deviation Formula")
body("The gaze detection algorithm quantifies the horizontal offset of the student's nose tip from the midpoint between the two eye inner corners, providing a robust proxy for head-turn-based gaze direction. The eye midpoint M_x is computed as:")
para("M_x  =  ( p₃₃.x  +  p₂₆₃.x )  /  2",bold=True,size=12,align="center",space_before=6,space_after=4,color=(79,70,229))
body("The gaze deviation is then:")
para("Deviation  =  | p₄.x  −  M_x |",bold=True,size=12,align="center",space_before=4,space_after=8,color=(79,70,229))
body("Where p₄ is the nose tip landmark and p₂₆₃ is the right eye inner corner landmark. The student is classified as gaze-distracted if the deviation exceeds 35% of the inter-eye distance: Deviation > 0.35 × (p₂₆₃.x − p₃₃.x). This threshold was empirically calibrated to minimise false positives from natural head micro-movements while reliably detecting intentional gaze aversion.")
fig("fig3_7_gaze.png","Fig 3.7 – Gaze Detection Algorithm Flow")

sub("3.4.4","RAG Pipeline")
body("The Retrieval-Augmented Generation pipeline processes student queries through a four-stage flow: embedding, retrieval, augmentation, and generation. During course ingestion (an offline process triggered by content administrators), video transcripts are segmented into 500-character chunks with 50-character overlaps using a sliding-window tokeniser. Each chunk is embedded using Google's text-embedding-004 model, producing a 768-dimensional dense vector representation. These vectors are upserted into a Pinecone serverless index with the course ID and chunk text stored as metadata.")
body("At query time, the student's natural language question is embedded using the same model, and a cosine similarity search retrieves the top-three most semantically proximate transcript chunks. Cosine similarity is computed as: sim(q,d) = (q·d) / (||q|| × ||d||). The three retrieved chunks are concatenated and injected into a structured Gemini 1.5 Flash prompt that explicitly instructs the model to answer based solely on the provided context, citing specific concepts from the retrieved text. This architecture guarantees that all AI responses are grounded in course material, eliminating hallucination entirely for in-scope queries.")
fig("fig3_8_rag.png","Fig 3.8 – RAG (Retrieval-Augmented Generation) Pipeline")

sub("3.4.5","WebRTC Signaling Flow")
body("Internixa's live meeting module establishes peer-to-peer video connections using the WebRTC standard with a Socket.IO-based signaling server. When a host creates a meeting room, the Socket.IO server registers the room ID. Each joining participant performs the following handshake: the joiner emits a join-room event; the server notifies existing peers; existing peers send SDP offer messages to the joiner via the server; the joiner generates SDP answers and returns them; both peers exchange ICE candidates discovered via a configured STUN server. Upon ICE negotiation completion, a direct P2P media channel is established between peers, and the Socket.IO signaling channel is used only for subsequent meeting control events (mute, leave, engagement updates).")
fig("fig3_9_webrtc.png","Fig 3.9 – WebRTC Signaling Diagram")

sub("3.4.6","Focus Points Algorithm")
body("The Focus Points (FP) scoring algorithm rewards genuine engagement behaviour across all platform interactions. The base score is computed from the ratio of active focus time to total session time, weighted by a course difficulty factor:")
para("FP  =  ( Active_Focus_Time / Total_Session_Time )  ×  100  ×  W",
     bold=True,size=12,align="center",space_before=6,space_after=8,color=(79,70,229))
body("Where W is a course weight factor ranging from 1.0 (introductory courses) to 2.0 (advanced technical courses). Bonus FP are awarded for supplementary engagement activities: +5 FP per chatbot interaction, +10 FP per puzzle completion, +15 FP per meeting participation. The total FP accumulated across all sessions feeds the platform leaderboard, which is sorted in descending order and refreshed in real-time via MongoDB change streams.")

sec("3.5","Module Description")

modules = [
    ("3.5.1","Module 1: AI Monitoring Engine",
     "The AI Monitoring Engine is the core differentiating component of Internixa. Implemented entirely in React using the MediaPipe JavaScript library, this module accesses the student's webcam via the getUserMedia API and processes each frame through the Face Mesh model at 30 FPS. The module maintains a rolling state machine with three states: ATTENTIVE, DISTRACTED, and ABSENT. State transitions are governed by the EAR and gaze deviation thresholds described in Section 3.4. The module emits attention state change events to the Course Player module and logs active/distracted time intervals to local state, which is persisted to the backend upon session completion via the POST /api/session/complete endpoint.",
     "The engine implements a hysteresis mechanism to prevent rapid state oscillation: a student must sustain the DISTRACTED state for at least three consecutive frames before a distraction event is triggered, and must sustain the ATTENTIVE state for at least two consecutive frames before the video resumes. This prevents the disruptive experience of the video pausing and resuming due to natural eye blinks or micro head movements. The module also renders a minimal HUD overlay on the course player, displaying a real-time attention indicator and cumulative focus percentage."),
    ("3.5.2","Module 2: Course Player with Smart Pause/Resume",
     "The Course Player module wraps an HTML5 video element with a React state machine that responds to attention events from the AI Monitoring Engine. When an ATTENTIVE → DISTRACTED transition is detected, the module calls video.pause() and displays an overlay prompting the student to look at the screen. When a DISTRACTED → ATTENTIVE transition is detected, the module calls video.play() and removes the overlay. Session timing is tracked using the browser's performance.now() API for millisecond-precision active time measurement.",
     "The module also integrates the Smart Study Sheet feature: upon video completion, a background API call to POST /api/summary/generate triggers the Gemini-powered transcript summarisation pipeline, and the resulting study sheet is displayed in a side panel alongside the video. Chapter markers and bookmarking functionality allow students to annotate key moments in the course timeline for later review."),
    ("3.5.3","Module 3: RAG Chatbot",
     "The RAG Chatbot module provides a context-locked AI assistant that appears as a collapsible panel within the course player interface. The chat interface is built with React and communicates with the FastAPI backend via a POST /api/chatbot/chat endpoint. Each request includes the student's question, the current course ID, and the session JWT. The backend validates the JWT, retrieves the Pinecone index corresponding to the course ID, executes the embedding and retrieval pipeline, constructs the augmented prompt, and streams the Gemini response back to the client using Server-Sent Events (SSE) for a real-time typing effect.",
     "A session-level interaction counter tracks the number of chatbot queries per session, incrementing the student's Focus Points by 5 per query to reward active engagement with course material. The chatbot interface includes a 'thumbs up/down' feedback mechanism that logs response quality ratings to MongoDB for continuous improvement purposes."),
    ("3.5.4","Module 4: WebRTC Meeting System",
     "The WebRTC Meeting System enables instructors to host live, interactive sessions with multiple participants simultaneously. The module is built using the browser's native RTCPeerConnection API for media transport and Socket.IO for the signaling layer. The full-mesh topology allows each participant to maintain a direct P2P connection with every other participant, ensuring minimal latency and no single-point-of-failure in the media path. The host interface includes a dedicated HUD panel that displays a real-time grid of participant video thumbnails annotated with individual attention scores derived from each participant's local AI monitoring engine.",
     "Participant attention data is transmitted to the meeting server via Socket.IO events at 1-second intervals, enabling the host to identify disengaged participants in real-time and intervene with targeted questions or prompts. Session statistics, including per-participant active time and engagement scores, are persisted to MongoDB at session end and are accessible via the Meeting Analytics dashboard."),
    ("3.5.5","Module 5: Gamification Engine",
     "The Gamification Engine manages the Focus Points economy and competitive leaderboard that incentivise consistent, genuine engagement across the platform. Focus Points are computed, validated, and stored entirely on the backend to prevent client-side manipulation. The FastAPI session completion endpoint receives raw active and total time values from the client, re-computes the FP score on the server using the canonical formula, and validates the computed score against reasonable bounds before persisting it to the student's MongoDB document.",
     "The leaderboard is implemented as a real-time ranked view over the MongoDB Users collection, sorted by cumulative FP score. The frontend fetches leaderboard data every 30 seconds and animates rank changes using Framer Motion to provide a visually dynamic competitive experience. Weekly and all-time leaderboard views are supported, with weekly scores reset automatically via a MongoDB scheduled trigger."),
    ("3.5.6","Module 6: Certificate Generation",
     "The Certificate Generation module produces tamper-proof PDF certificates using Python's ReportLab library. Certificate issuance is gated by the session completion endpoint: if the computed engagement score is below the 70% threshold, the endpoint returns a 402 status with a motivational prompt rather than generating a certificate. When the threshold is met, the endpoint invokes the certificate generation function, which creates a ReportLab Canvas object, renders the Internixa digital seal, embeds the student's name, course title, completion date, and verified engagement score, applies a diagonal watermark, and outputs the PDF as a binary stream.",
     "The PDF blob is stored in MongoDB GridFS and a download URL is returned to the client. The certificate is simultaneously added to the student's certificate gallery within the platform. Each certificate includes a unique verification ID that can be validated via a public endpoint, enabling recruiters and employers to independently verify certificate authenticity."),
    ("3.5.7","Module 7: Smart Study Sheets",
     "The Smart Study Sheet module uses Google Gemini 1.5 Flash to generate concise, AI-curated summaries of course transcript content immediately upon session completion. The module sends the full transcript of the completed course segment to the Gemini API with a structured prompt requesting a bullet-pointed summary organised by key concept, with emphasis on the topics identified as high-focus by the student's attention data. The resulting study sheet is formatted in Markdown and rendered in the platform's study sheet viewer.",
     "Study sheets are personalised to the student's attention patterns: topics from segments where the student's focus score was below 60% are highlighted with a review recommendation indicator, directing the student's revision efforts toward areas of demonstrated weakness. All generated study sheets are stored in MongoDB and are accessible from the student's learning history dashboard."),
    ("3.5.8","Module 8: Recruiter Portal",
     "The Recruiter Portal provides a dedicated interface for registered recruiters to post, manage, and review applications for internship opportunities. Recruiters authenticate using the same JWT-based authentication system as students, but are assigned a recruiter role that grants access to a separate dashboard with CRUD operations for internship listings. Each listing includes fields for title, company name, location (remote/in-person), stipend range, duration, required skills, and application deadline.",
     "Students can browse active internship listings from the Explore page and submit applications directly through the platform. Application data, including the student's profile, Focus Points ranking, and completed certificates, is automatically compiled into a structured applicant profile accessible to the recruiter. This integration creates a closed-loop employment pathway that directly rewards high-engagement learners with internship opportunities matched to their demonstrated competencies."),
]

for num,title,p1,p2 in modules:
    sub(num,title); body(p1); body(p2)

fig("fig3_10_cert.png","Fig 3.10 – Certificate Generation Flow")

doc.save(OUT)
print("Chapter 3 done. Saved.")
